// =============================================
// scripts/data.js - Product & Category Data
// =============================================

const CATEGORIES = [
    { id: 'all', name: 'همه', icon: '' },
    { id: 'doner', name: 'دونر', icon: '' },
    { id: 'pizza', name: 'پیتزا', icon: '' },
    { id: 'burger', name: 'برگر', icon: '' },
    { id: 'appetizer', name: 'پیش‌غذا', icon: '' },
    { id: 'drink', name: 'نوشیدنی', icon: '' },
];

const PRODUCTS = [
    {
        id: 'doner-chicken-special',
        name: 'دونر مرغ ویژه',
        category: 'doner',
        description: 'گوشت مرغ مزه‌دار شده با ادویه‌های مخصوص ترکی، کباب شده روی آتش و سرو با نان تازه و سبزیجات',
        price: 185000,
        image: 'https://alogoosht.com/mag/wp-content/uploads/2023/07/%DA%A9%D8%A8%D8%A7%D8%A8-%D8%AA%D8%B1%DA%A9%DB%8C.webp',
        badge: 'پرفروش',
        isFeatured: true,
        available: true,
        prepTime: '۱۵ دقیقه',
        rating: 4.8,
    },
    {
        id: 'doner-meat-turkish',
        name: 'دونر گوشت ترکی',
        category: 'doner',
        description: 'گوشت گوساله لایه‌لایه شده با چاشنی مخصوص، برشته و آبدار همراه با نان لواش داغ',
        price: 225000,
        image: './images/doner_gosht_torky.jpg',
        badge: 'محبوب',
        isFeatured: false,
        available: true,
        prepTime: '۲۰ دقیقه',
        rating: 4.9,
    },
    {
        id: 'doner-mix',
        name: 'دونر میکس',
        category: 'doner',
        description: 'ترکیبی از دونر مرغ و گوشت، سرو شده با سیب‌زمینی سرخ‌کرده، سس مخصوص و سالاد',
        price: 265000,
        image: 'https://alogoosht.com/mag/wp-content/uploads/2023/07/%DA%A9%D8%A8%D8%A7%D8%A8-%D8%AA%D8%B1%DA%A9%DB%8C.webp',
        badge: 'پیشنهاد ویژه',
        isFeatured: false,
        available: true,
        prepTime: '۱۸ دقیقه',
        rating: 4.7,
    },
    {
        id: 'doner-plate',
        name: 'بشقاب دونر',
        category: 'doner',
        description: 'بشقاب کامل دونر با برنج زعفرانی، گریل گوجه، فلفل کبابی و سالاد شیرازی',
        price: 295000,
        image: './images/boshghab_doner.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۲۵ دقیقه',
        rating: 4.6,
    },
    {
        id: 'pizza-turkish',
        name: 'پیتزا ترکی',
        category: 'pizza',
        description: 'پیتزا به سبک ترکی با گوشت دونر، پنیر موزارلا، فلفل دلمه‌ای و زیتون سیاه',
        price: 210000,
        image: './images/pitzza_torky.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۲۰ دقیقه',
        rating: 4.5,
    },
    {
        id: 'pizza-pepperoni',
        name: 'پیتزا پپرونی',
        category: 'pizza',
        description: 'پیتزا پپرونی کلاسیک با پنیر فراوان، سس گوجه‌فرنگی خانگی و خمیر نازک برشته',
        price: 195000,
        image: './images/pitzza_peperony.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۱۸ دقیقه',
        rating: 4.4,
    },
    {
        id: 'burger-charcoal',
        name: 'برگر زغالی',
        category: 'burger',
        description: 'برگر گوشت خالص گریل شده روی ذغال با پنیر چدار، کاهو، گوجه و سس باربیکیو',
        price: 235000,
        image: './images/beger_zoghaly.jpg',
        badge: 'پرطرفدار',
        isFeatured: false,
        available: true,
        prepTime: '۱۵ دقیقه',
        rating: 4.7,
    },
    {
        id: 'cheeseburger-special',
        name: 'چیزبرگر مخصوص',
        category: 'burger',
        description: 'برگر دوبل با دو لایه پنیر گودا، بیکن، پیاز کاراملیزه و نان بریوش طلایی',
        price: 275000,
        image: './images/chizberger.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۲۰ دقیقه',
        rating: 4.8,
    },
    {
        id: 'fries-special',
        name: 'سیب‌زمینی مخصوص',
        category: 'appetizer',
        description: 'سیب‌زمینی خلالی ترد و طلایی با چاشنی مخصوص تاب دونر و سس پنیر',
        price: 85000,
        image: './images/sib_zamini.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۱۰ دقیقه',
        rating: 4.3,
    },
    {
        id: 'fried-mushrooms',
        name: 'قارچ سوخاری',
        category: 'appetizer',
        description: 'قارچ‌های تازه سوخاری شده با پودر سوخاری ادویه‌دار، سرو با سس مخصوص',
        price: 95000,
        image: './images/gharch.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: '۱۲ دقیقه',
        rating: 4.2,
    },
    {
        id: 'doogh-local',
        name: 'دوغ محلی',
        category: 'drink',
        description: 'دوغ گازدار سنتی با نعناع تازه، خنک و گوارا',
        price: 35000,
        image: 'https://files.namnak.com/users/kk/aup/201912/207_pics/%D8%AF%D9%88%D8%BA-%D9%85%D8%AD%D9%84%DB%8C.webp',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: 'آماده',
        rating: 4.5,
    },
    {
        id: 'soda-can',
        name: 'نوشابه قوطی',
        category: 'drink',
        description: 'نوشابه خنک (کوکاکولا / فانتا / اسپرایت) - لطفاً نوع مورد نظر را در یادداشت سفارش ذکر کنید',
        price: 28000,
        image: './images/noshabe.jpg',
        badge: '',
        isFeatured: false,
        available: true,
        prepTime: 'آماده',
        rating: 4.0,
    },
];

function getProductById(id) {
    return PRODUCTS.find(p => p.id === id);
}

function getAvailableCategories() {
    const used = new Set(PRODUCTS.map(p => p.category));
    return CATEGORIES.filter(c => c.id === 'all' || used.has(c.id));
}